### ISSUE TITLE
Failed to open

### ISSUE THREAD

**Issue by kopirobusta** [viperbluff/PortWitness#1]
[!]Searching For Sub-Domains ........

portwitness.sh: line 96: output.txt: No such file or directory
[!] IP's for all sub-domains generated in ./Sublist3r/ip_urlBug.txt
Failed to open input file ip_urlBug.txt for reading
QUITTING!
cat: port_status_urlBug.txt: No such file or directory
[!] All the active IP's are generated in ./Sublist3r/result.txt

[!]The Following sub-domains are Scanned:
portwitness.sh: line 96: output.txt: No such file or directory
[!]List of all the active sub-domains is stored under ./Sublist3r/active_domain.txt

**Comment by viperbluff** [comment]
Could you please elaborate on the steps of reproduction?

**Comment by peyot22** [comment]
how to make fast find subdomain sir ?
i have so slow and have error

typeError: Unicode-objects must be encoded before hashing

hiw to fix

**Comment by viperbluff** [comment]
You can run the python version of portwitness. I have made available.Its fast and more reliable

**Comment by peyot22** [comment]
PortWitness[Python].py viu.com
Traceback (most recent call last):
  File "PortWitness[Python].py", line 52, in <module>
    main()
  File "PortWitness[Python].py", line 50, in main
    Sublist3r(domain)
  File "PortWitness[Python].py", line 12, in Sublist3r
    "test3.txt"],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by viperbluff** [comment]
Hello @peyot22 , could you please run the python version again and let me know the output?
I have made some changes. :-)
